"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const field_s_crops_controller_1 = require("../controller/field's_crops_controller");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const fieldCropsRouter = (0, express_1.Router)();
fieldCropsRouter.post("/", authMiddleware_1.authenticateUser, (0, authMiddleware_1.authorizeRole)("MANAGER", "ADMIN", "SCIENTIST"), field_s_crops_controller_1.createFieldCrop);
fieldCropsRouter.get("/", authMiddleware_1.authenticateUser, (0, authMiddleware_1.authorizeRole)("MANAGER", "ADMIN", "SCIENTIST"), field_s_crops_controller_1.getAllFieldCrops);
fieldCropsRouter.delete("/:fieldId/:cropId", authMiddleware_1.authenticateUser, (0, authMiddleware_1.authorizeRole)("MANAGER", "ADMIN", "SCIENTIST"), field_s_crops_controller_1.deleteFieldCrop);
exports.default = fieldCropsRouter;
