"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const vehicle_controller_1 = require("../controller/vehicle_controller");
const authMiddleware_1 = require("../middlewares/authMiddleware");
const vehicleRouter = (0, express_1.Router)();
vehicleRouter.post("/", authMiddleware_1.authenticateUser, (0, authMiddleware_1.authorizeRole)("MANAGER", "ADMIN", "SCIENTIST"), vehicle_controller_1.createVehicle);
vehicleRouter.get("/", authMiddleware_1.authenticateUser, (0, authMiddleware_1.authorizeRole)("MANAGER", "ADMIN", "SCIENTIST"), vehicle_controller_1.getAllVehicles);
vehicleRouter.put("/:id", authMiddleware_1.authenticateUser, (0, authMiddleware_1.authorizeRole)("MANAGER", "ADMIN", "SCIENTIST"), vehicle_controller_1.updateVehicle);
vehicleRouter.delete("/:id", authMiddleware_1.authenticateUser, (0, authMiddleware_1.authorizeRole)("MANAGER", "ADMIN", "SCIENTIST"), vehicle_controller_1.deleteVehicle);
exports.default = vehicleRouter;
